# Configurasi Situs
title: Project
description: Project yang pernah saya kerjakan
baseurl: "/nama-sub-direktori-jekyll" # jika situs di-host di sub-direktori

# Pengaturan Build & Serve
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Pengaturan URL
url: "https://github.com/Elxixau?tab=repositories" # Ganti dengan URL repositori GitHub Anda

# Pengaturan Autor
author:
  name: Indra Parlindungan Hutahaean
  email: indra90078@gmail.com

# Pengaturan Lainnya
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
